### ISSUE TITLE
Add documentation on how to add or initialise custom renderers

### ISSUE THREAD

**Issue by sambunting** [cenk1cenk2/nuxt-docs#2]
First off - thank you for Listr2 and this documentation, I think it's amazing! I figured I'd open an issue here as apposed to the actual Listr repo since it seems to be more focused on documentation if that's ok?

I've spent the past hour or so trying to create my own custom renderer, but I've kinda struggled with how I would actually use the renderer itself.

I could be completely and utterly missing something - but it would be nice if there could be a section on the ["Create Your Own Renderer" page](https://listr2.kilic.dev/renderers/custom-renderer).

I'd add it myself in a pull-request - but I don't know how to do it 🙃

**Comment by sambunting** [comment]
I've managed to figure it out! I've also added a bit to the documentation if that's ok?

I've opened a pull request for you to have a look #3

**Comment by cenk1cenk2** [comment]
Hey @sambunting ,

Sorry I could not reply earlier and save you the hassle. But yeah it makes sense to add that there too.

Thank you for your work on this.
